### ISSUE TITLE
Vanilla APIS: "alternative schuh ids" property should not be obligatory

### ISSUE THREAD

**Issue by GVogeler** [acdh-oeaw/apis-instance-manmax#18]
Gendering Maximilian: "Beim Anlegen im normalen Interface (nicht Factoid Editor) muss man “alternative schuh ids” angeben, sonst geht das Speichern nicht."

**Comment by richardhadden** [comment]
True; it's some weirdness between the form generator and having a Postgres ArrayField (it should be not required, but for some reason is)

Hacky workaround: enter a comma in the field

**Comment by GVogeler** [comment]
Matthias has any ideas about this?

**Comment by richardhadden** [comment]
I don't think so (no one has ever used this before as far as I know). The solution would just be to provide a default, and ensure the field isn't manually editable.

**Comment by richardhadden** [comment]
I need to push the update with this, but it's solved (I added the "editable=false" flag to the CharField, but not to the wrapping ArrayField). The field doesn't even show up in the APIS interface now.
