### ISSUE TITLE
add groupofpersons as entity to the relationship "performed by" (aufgeführt von)

### ISSUE THREAD

**Issue by GVogeler** [acdh-oeaw/apis-instance-manmax#44]
e.g.: "1497 führt Joseph Grünpeck mit seinen Schülern vor Maximilian in Augsburg das Tugendspiel Virtus et Fallacicaptrix auf " (Joseph Grünpeck an his students perform a play in front of Maximilian in Augusburg on 1497). Currently you can link a performance of a text only to institutions, persons and foundations:  https://github.com/acdh-oeaw/apis-instance-manmax/blob/7d7e5c4119364ce605354e985879cea3aab2f531/apis_ontology/models.py#L1475-L1480

**Comment by richardhadden** [comment]
Done
